controllers:
  config:
    body:
      control_type: thruster
      state: state
      position_setpoint: body_position_setpoint
      velocity_setpoint: body_velocity_setpoint
      command: body_command
      dynamic_reconfigure: False
      cascaded_position: False
    x:
      velocity: {p: 150, i: 100, d: 0}
      position: {p: 100, i: 5, d: 100}
    y:
      velocity: {p: 150, i: 100, d: 0}
      position: {p: 100, i: 5, d: 100}
    z:
      velocity: {p: 150, i: 100, d: 0}
      position: {p: 100, i: 5, d: 100}
    pitch:
      velocity: {p: 150, i: 100, d: 0}
      position: {p: 100, i: 5, d: 100}
    roll:
      velocity: {p: 150, i: 100, d: 0}
      position: {p: 100, i: 5, d: 100}
    yaw:
      velocity: {p: 150, i: 100, d: 0}
      position: {p: 100, i: 5, d: 100}
